# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_image',
        ),
    ]
