# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('blog', '0005_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
